name: voyager
description: "A mentorship portal."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0 # Updated for compatibility
  supabase_flutter: ^2.8.4
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.1
  icons_plus: ^5.0.0
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^3.10.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  firebase_auth: ^5.5.0
  http: ^1.3.0
  get: ^4.6.6
  google_sign_in: ^6.2.2
  awesome_snackbar_content: ^0.1.5
  shared_preferences: ^2.3.5
  cloud_firestore: ^5.6.1
  flutter_launcher_icons: ^0.14.2
  google_nav_bar: ^5.0.7
  font_awesome_flutter: ^10.1.0
  multiselect: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/application_images/eduvate_cover.png
  android_12:
    icon_background_color: "#ffffff"
    image: assets/images/application_images/eduvate_cover.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/login_images/
    - assets/images/forget_password/
    - assets/images/signup_images/
    - assets/images/otp_images/
    - assets/images/email_verification/
    - assets/images/splash_screen/
    - assets/images/application_images/

flutter_icons:
  anroid: true
  ios: true
  image_path: "assets/images/application_images/eduvate_logo.png"
